---
dataset_name: ImageNet
model_name: Resnet50
distributed_algorithm: GTG_shapley_value
optimizer_name: SGD
worker_number: 8
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
batch_size: 128
learning_rate: 0.01
...
