---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: interval_shapley_value
optimizer_name: SGD
worker_number: 8
batch_size: 64
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
learning_rate: 0.1

...
