---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: interval_shapley_value
optimizer_name: SGD
worker_number: 6
batch_size: 64
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
learning_rate: 0.1
algorithm_kwargs:
  lambda: 1
  round_trunc_threshold: 0.005

dataset_sampling: iid

#dataset_sampling: iid_split_and_sample
#dataset_sampling_kwargs:
#   sample_probs:
#      - {0: 0.1, 1: 0.1, 2: 0.1, 3: 0.1, 4: 0.1, 5: 0.1, 6: 0.1, 7: 0.1, 8: 0.1, 9: 0.1}
#      - {0: 0.1, 1: 0.1, 2: 0.1, 3: 0.1, 4: 0.1, 5: 0.1, 6: 0.1, 7: 0.1, 8: 0.1, 9: 0.1}
#      - {0: 0.3, 1: 0.3, 2: 0.3, 3: 0.3, 4: 0.3, 5: 0.3, 6: 0.3, 7: 0.3, 8: 0.3, 9: 0.3}
#      - {0: 0.3, 1: 0.3, 2: 0.3, 3: 0.3, 4: 0.3, 5: 0.3, 6: 0.3, 7: 0.3, 8: 0.3, 9: 0.3}
#      - {0: 0.6, 1: 0.6, 2: 0.6, 3: 0.6, 4: 0.6, 5: 0.6, 6: 0.6, 7: 0.6, 8: 0.6, 9: 0.6}
#      - {0: 0.6, 1: 0.6, 2: 0.6, 3: 0.6, 4: 0.6, 5: 0.6, 6: 0.6, 7: 0.6, 8: 0.6, 9: 0.6}
#      - {0: 0.9, 1: 0.9, 2: 0.9, 3: 0.9, 4: 0.9, 5: 0.9, 6: 0.9, 7: 0.9, 8: 0.9, 9: 0.9}
#      - {0: 0.9, 1: 0.9, 2: 0.9, 3: 0.9, 4: 0.9, 5: 0.9, 6: 0.9, 7: 0.9, 8: 0.9, 9: 0.9}

#dataset_sampling: iid_split_and_flip
#dataset_sampling_kwargs:
#  flip_percent:
#    - 0.01
#    - 0.01
#    - 0.1
#    - 0.1
#    - 0.5
#    - 0.5
#    - 0.9
#    - 0.9

#dataset_sampling: dirichlet_split
#dataset_sampling_kwargs:
#  concentration: 0.5
...
