---
dataset_name: ImageNet
model_name: Resnet50
distributed_algorithm: interval_shapley_value
optimizer_name: SGD
worker_number: 6
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
batch_size: 128
learning_rate: 0.01
algorithm_kwargs:
  lambda: 1
  round_trunc_threshold: 0.005

dataset_sampling: iid

#dataset_sampling: iid_split_and_sample
#dataset_sampling_kwargs:
#   sample_probs:
#      - {0: 0.1, 1: 0.1, 2: 0.1, 3: 0.1, 4: 0.1, 5: 0.1, 6: 0.1, 7: 0.1, 8: 0.1, 9: 0.1}
#      - {0: 0.1, 1: 0.1, 2: 0.1, 3: 0.1, 4: 0.1, 5: 0.1, 6: 0.1, 7: 0.1, 8: 0.1, 9: 0.1}
#      - {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5, 5: 0.5, 6: 0.5, 7: 0.5, 8: 0.5, 9: 0.5}
#      - {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5, 4: 0.5, 5: 0.5, 6: 0.5, 7: 0.5, 8: 0.5, 9: 0.5}
#      - {0: 0.9, 1: 0.9, 2: 0.9, 3: 0.9, 4: 0.9, 5: 0.9, 6: 0.9, 7: 0.9, 8: 0.9, 9: 0.9}
#      - {0: 0.9, 1: 0.9, 2: 0.9, 3: 0.9, 4: 0.9, 5: 0.9, 6: 0.9, 7: 0.9, 8: 0.9, 9: 0.9}


#dataset_sampling: iid_split_and_flip
#dataset_sampling_kwargs:
#  flip_percent:
#    - 0.1
#    - 0.1
#    - 0.5
#    - 0.5
#    - 0.9
#    - 0.9
...
